---
sudo: false
language: ruby
cache: bundler
rvm:
  - 3.1.0
  - 3.0.4
  - 2.7.5
  - 2.6.9
script:
  - bundle exec rspec spec/
before_install:
  - gem install -v 2.0.1 bundler
  - bundle update --bundler
